AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM file to create lambda function.

Parameters:
  IAMRole:
    Type: String
    Description: iam role arn
  SlackWebhookUrl:
    Type: String
    Description: slack incoming webhook url
  SlackIcon:
    Type: String
    Default: ":moneybag:"
    Description: slack bot icon emoji
  SlackChannel:
    Type: String
    Description: slack channel
  SlackBotName:
    Type: String
    Default: "aws cost report"
    Description: slack bot name
  NotifyThreasholdGood:
    Type: Number
    Default: 5.0
    Description: threashold value to notify by "good" color
  NotifyThreasholdWarn:
    Type: Number
    Default: 15.0
    Description: threashold value to notify by "warn" color

Globals:
  Function:
    Runtime: python3.6
    Timeout: 10
    MemorySize: 128
    Environment:
      Variables:
        SLACK_WEBHOOK_URL: !Ref SlackWebhookUrl
        SLACK_ICON: !Ref SlackIcon
        SLACK_CHANNEL: !Ref SlackChannel
        SLACK_BOT_NAME: !Ref SlackBotName
        NOTIFY_THRESHOLD_GOOD: !Ref NotifyThreasholdGood
        NOTIFY_THRESHOLD_WARN: !Ref NotifyThreasholdWarn

Resources:
  CostCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_package.zip
      Handler: aws_cost_notifier.lambda_handler
      Role: !Ref IAMRole

      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 * * ? *)
